### PR TITLE
use `childProcess.ChildProccess` polyfill

### PR DESCRIPTION
**Pull request by sindresorhus**
Doesn't spawn when it's available (io.js 2.2.0+), so will be faster than the current.

https://github.com/sindresorhus/child-process-ctor

### CODE REVIEW

**Comment by bcoe** [comment]
@sindresorhus I'll ping Isaac about this, seems like a great patch.

**Comment by isaacs** [comment]
easier to just set it to `child_process.ChildProcess` to begin with. Thanks, tho.

**Comment by isaacs** [comment]
Oh, actually, whether using this module or pulling in the ctor off the module, I'm getting a bunch of failures.  It seems like what's being exported isn't identical to what's actually used?

**Comment by sindresorhus** [comment]
> easier to just set it to child_process.ChildProcess to begin with

That would break backwards compatible with Node.js 0.10 and 0.12, though.

> Oh, actually, whether using this module or pulling in the ctor off the module, I'm getting a bunch of failures. It seems like what's being exported isn't identical to what's actually used?

I added some more tests proving what's returned by my module is the exact same as `child_process.ChildProcess`: https://github.com/sindresorhus/child-process-ctor/commit/ca6213296e7d296b28ea11f66c757e83a93429da#diff-1dd241c4cd3fd1dd89c570cee98b79ddR13

**Comment by isaacs** [comment]
Yeah, I have no idea why it's behaving differently.  It's the same exact object.  However, if you try to patch the prototype before the first child proc is created, it doesn't work.  So weird!

**Pull request closed without merging**
